namespace XXLMod3.Core
{
    public enum StanceTab
    {
        Catch,
        Grabs,
        GrabsOnButton,
        Grinding,
        GrindOnButton,
        InAir,
        Manual,
        ManualSwitch,
        NoseManual,
        NoseManualSwitch,
        ManualOnButton,
        Powerslide,
        Primo,
        PrimoSetup,
        PrimoSetupNollie,
        Pushing,
        PushingMongo,
        PushingSwich,
        PushingSwitchMongo,
        Riding,
        RidingSwitch,
        Setup,
        SetupNollie,
        SetupSwitch,
        SetupFakie,
        OnButton
    }
}